language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false
notifications:
  on_success:
    - change
  on_failure:
    - change
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  apt:
    packages:
      - graphviz
